#pragma once

#include "KofPack.h"

#include "KofDialogEx.h"
#include "KofDlgImpl.h"
#include "KofStyleHelper.h"
#include "KofMFCButton.h"
#include "KofMFCEdit.h"
#include "KofComboBox.h"
#include "KofStatic.h"
#include "KofProgressCtrl.h"
#include "KofMFCColorButton.h"
#include "KofMFCSpinButtonCtrl.h"
#include "KofRichEditCtrl.h"
#include "KofMFCFontComboBox.h"
#include "KofMFCMaskedEdit.h"
#include "KofGroup.h"
#include "KofMFCTabCtrl.h"
#include "KofMFCPropertySheet.h"
#include "KofMFCPropertyPage.h"
#include "KofFormView.h"
#include "KofMessageBox.h"
#include "KofMFCMenuButton.h"