//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by KofPackRes.rc
//
#define AQUA_IDB_OFFICE2007_RIBBON_BUTTONS_PUSH     102
#define BLUE_IDB_OFFICE2007_RIBBON_BUTTONS_PUSH     103
#define BLACK_IDB_OFFICE2007_RIBBON_BUTTONS_PUSH    104
#define SILVER_IDB_OFFICE2007_RIBBON_BUTTONS_PUSH   105
#define AQUA_IDB_OFFICE2007_RIBBON_BUTTONS_RADIO	106
#define BLUE_IDB_OFFICE2007_RIBBON_BUTTONS_RADIO	107
#define BLACK_IDB_OFFICE2007_RIBBON_BUTTONS_RADIO	108
#define SILVER_IDB_OFFICE2007_RIBBON_BUTTONS_RADIO	109

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        106
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
